apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::114403655685:role/eksctl-Pulse-cluster-nodegroup-pul-NodeInstanceRole-4LrwcLAu8KsJ
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - userarn: arn:aws:iam::114403655685:user/sai-admin
      username: admin
      groups:
      - system:masters

kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-26T12:07:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1171"
  uid: 55ddcfe0-757d-42e4-b346-1fb035e77a8c