apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"medication-suggest-ai-service","namespace":"qa"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8000}],"selector":{"app":"medication-suggest-ai"},"type":"LoadBalancer"}}
  creationTimestamp: "2026-05-22T07:05:49Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: medication-suggest-ai-service
  namespace: qa
  resourceVersion: "409067"
  uid: bcff4657-3cad-4ecd-a051-4ce3a4c010d7
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.137.150
  clusterIPs:
  - 10.100.137.150
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31332
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: medication-suggest-ai
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: abcff46573cad4ecda0514ce3a4c010d-300465193.ap-south-1.elb.amazonaws.com
