apiVersion: apps/v1
kind: Deployment

metadata:
  name: medication-suggest-ai
  namespace: qa

spec:
  replicas: 1

  selector:
    matchLabels:
      app: medication-suggest-ai

  template:
    metadata:
      labels:
        app: medication-suggest-ai

    spec:
      containers:
        - name: medication-suggest-ai

          image: 114403655685.dkr.ecr.ap-south-1.amazonaws.com/medication-suggest-ai:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY

            - name: DEEPGRAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DEEPGRAM_API_KEY