apiVersion: apps/v1
kind: Deployment

metadata:
  name: medi-suggest-ai
  namespace: qa

spec:
  replicas: 1

  selector:
    matchLabels:
      app: medi-suggest-ai

  template:
    metadata:
      labels:
        app: medi-suggest-ai

    spec:
      containers:
        - name: medi-suggest-ai

          image: 114403655685.dkr.ecr.ap-south-1.amazonaws.com/medication-suggest-ai:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: OLLAMA_MODEL
              value: "phi3:mini"

            - name: OLLAMA_BASE_URL
              value: "http://ollama:11434"

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"

            limits:
              memory: "1Gi"
              cpu: "500m"