apiVersion: v1
kind: Service

metadata:
  name: medi-suggest-ai-service
  namespace: qa

spec:
  selector:
    app: medi-suggest-ai

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

  type: LoadBalancer