apiVersion: v1
kind: Service
metadata:
  name: medi-suggest-ai
  namespace: qa
  labels:
    app: medi-suggest-ai
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  type: ClusterIP
  selector:
    app: medi-suggest-ai