apiVersion: v1
kind: Service

metadata:
  name: medi-suggest-ai-service

spec:
  type: LoadBalancer

  selector:
    app: medi-suggest-ai

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000