apiVersion: v1
kind: Service
metadata:
  name: medi-suggest-ai
  namespace: qa
  labels:
    app: medi-suggest-ai
    environment: qa
spec:
  selector:
    app: medi-suggest-ai
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001