name: Deploy QA Environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to QA
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Login to AWS ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t medication-suggest-ai .

      # Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag medication-suggest-ai:latest \
          114403655685.dkr.ecr.ap-south-1.amazonaws.com/medication-suggest-ai:latest

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push 114403655685.dkr.ecr.ap-south-1.amazonaws.com/medication-suggest-ai:latest

      # Configure Kubeconfig
      - name: Configure Kubeconfig
        shell: bash
        run: |
          cat > kubeconfig.yaml << 'EOF'
          ${{ secrets.RIMS_KUBE_CONFIG_QA }}
          EOF

          export KUBECONFIG=$PWD/kubeconfig.yaml

          kubectl get nodes

      # Deploy to Kubernetes
      - name: Deploy to QA
        run: |
          export KUBECONFIG=$PWD/kubeconfig.yaml

          kubectl apply -f .k8s/qa/namespace.yaml
          kubectl apply -f .k8s/qa/deployment.yaml
          kubectl apply -f .k8s/qa/service.yaml

          kubectl rollout restart deployment medication-suggest-ai -n qa