name: Create QA Kubernetes Objects

on:
  workflow_dispatch:

jobs:
  create-k8s-objects:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure Kubeconfig
        shell: bash
        run: |
          cat > kubeconfig.yaml << 'EOF'
          ${{ secrets.RIMS_KUBE_CONFIG_QA }}
          EOF

          export KUBECONFIG=$PWD/kubeconfig.yaml

          kubectl config current-context
          kubectl get nodes

      - name: Create Kubernetes Objects
        run: |
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl apply -f .k8s/qa/deployment.yaml
          kubectl apply -f .k8s/qa/service.yaml